<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use dElt4\TimeBundle\Entity\Project;
use dElt4\TimeBundle\Entity\ProjectHasUser;
use Doctrine\Common\Collections\ArrayCollection;
use Sonata\UserBundle\Entity\BaseUser as BaseUser;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser
{
    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var ProjectHasUsers
     */
    protected $projectHasUsers;

    /**
     * @var double
     */
    protected $tjm;

    public function __construct()
    {
        parent::__construct();
        $this->projectHasUsers = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    public function setProjectHasUsers(array $projectHasUsers) {
        if (count($projectHasUsers) > 0) {
            foreach ($projectHasUsers as $element) {
                $this->addProjectHasUser($element);
            }
        }
    }

    public function addProjectHasUser(ProjectHasUser $projectHasUser) {
        $this->projectHasUsers->add($projectHasUser);

        return $this;
    }

    public function removeProjectHasUser(ProjectHasUser $projectHasUser) {
        $this->projectHasUsers->removeElement($projectHasUser);

        return $this;
    }

    public function clearProjectHasUsers() {
        $this->projectHasUsers->clear();

        return $this;
    }

    public function getProjectHasUsers() {
        return $this->projectHasUsers;
    }
}