<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use dElt4\TimeBundle\Entity\Project;
use Sonata\UserBundle\Entity\BaseUser as BaseUser;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser
{
    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var Project
     */
    protected $projects;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    public function setProjects(array $projects) {
        if (count($projects) > 0) {
            foreach ($projects as $element) {
                $this->addProject($element);
            }
        }
    }

    public function addProject(Project $project) {
        if (count($this->projects) > 0) {
            $found = false;
            foreach ($this->projects as $tmp) {
                if ($tmp->getTitle() === $project->getTitle()) {
                    $found = true;
                }
            }
            if (!$found) {
                $this->projects[] = $project;
            }
        }

        return $this;
    }

    public function removeProject(Project $project) {
        $tmps = array();
        if (count($this->projects) > 0) {
            foreach ($this->projects as $tmp) {
                if ($tmp->getTitle() !== $project->getTitle()) {
                    $tmps[] = $tmp;
                }
            }
            $this->projects = $tmps;
        }

        return $this;
    }

    public function clearProjects() {
        $this->projects->clear();

        return $this;
    }

    public function getProjects() {
        return $this->projects;
    }
}