<?php

namespace dElt4\TimeBundle\Entity;

use CalendR\Event\Provider\ProviderInterface;
use Doctrine\ORM\EntityRepository;
use Doctrine\DBAL\Types\Type;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    /**
     * Return events that matches to $begin && $end
     * $end date should be exclude
     *
     * @param \DateTime $begin
     * @param \DateTime $end
     * @param array $options
     */
    public function getEvents(\DateTime $begin, \DateTime $end, array $options = array())
    {
        $qb = $this->createQueryBuilder('e');


        return $qb
            ->where('e.begin >= :start')
            ->andWhere('e.end <= :end')
            ->setParameter('start', $begin, Type::DATETIME)
            ->setParameter('end', $end, Type::DATETIME)
            ->orderBy('e.begin')
            ->getQuery()
            ->getResult();
    }
}
