<?php

namespace dElt4\TimeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectHasUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectHasUserRepository extends EntityRepository
{
}
